# Generated by Django 3.1.7 on 2021-03-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTodo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('contant', models.CharField(max_length=500)),
                ('time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
